source/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView, VerifyAccount
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),
    path('verify/', VerifyAccount.as_view(), name='verify'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView, TOTPPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),
    path('enable_two_fa', TOTPPageView.as_view(), name='enable_two_fa'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/ballot/urls.py
from django.urls import path
from . import views

app_name = 'ballot'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('seal/', views.seal, name='seal')
]

source/simulation/urls.py
from django.urls import path
from . import views

app_name = 'simulation'
urlpatterns = [
    path('generate/', views.generate, name='generate'),
    path('generate_votes/', views.generate_votes, name='generate_votes'),
    path('seal/', views.seal, name='seal'),
    path('transactions/', views.transactions, name='transactions'),
    path('blockchain/', views.blockchain, name='blockchain'),
    path('block/<str:block_hash>/', views.block_detail, name='block_detail'),
    path('verify/', views.verify, name='verify'),
    path('sync/', views.sync, name='sync'),
    path('sync_with_firebase/', views.sync_with_firebase, name='sync_with_firebase'),
    path('sync_block/<int:block_id>/', views.sync_block, name='sync_block'),
]

source/main/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import Activation
from simulation.models import Election, Candidate


class IndexPageView(LoginRequiredMixin, TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        active_users = Activation.objects.filter(user_id = self.request.user.id)
        if(len(active_users)):
            context['voting_allowed'] = Activation.objects.filter(user_id = self.request.user.id)[0].voting_allowed
            context['election'] = Election.objects.filter(is_open = True).first()
            context['closed_election'] = Election.objects.filter(is_open = False).first()
        return context

class TOTPPageView(LoginRequiredMixin, TemplateView):
    template_name = 'main/2fa.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['private_key'] = Activation.objects.filter(user_id = self.request.user.id)[0].private_key_ecc
        private_key_ecc = Activation.objects.filter(user_id = self.request.user.id)[0]
        private_key_ecc.private_key_ecc = 'PRIVATE'
        private_key_ecc.save()
        return context

class ChangeLanguageView(TemplateView):
    template_name = 'main/change_language.html'

source/content/templates/main/2fa.html
{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% get_current_language as language_code %}
{% if user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <title>
    Blockchain Based Voting
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- CSS Files -->
  <link href="{% static 'css/soft-ui-dashboard.css' %}?v=1.0.2" rel="stylesheet" />
</head>

<body class="g-sidenav-show   bg-white">
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0  z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="{% url 'index' %}">
              Blockchain Based Voting
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>
  <section>
    <div class="page-header section-height-75">
      <div class="container">
        <div class="row" style="margin-left: -100px; margin-top: 120px;">
            <h4>{% trans 'Enable 2-FA on your account' %}</h4>
            {% with "/media/"|add:user.username|add:"_qr.png" as qr_dir %}
            <div class="col-12">
                <img src="{{ qr_dir }}">
                <br><br>
                <h5>Scan the above QR code on your 2-FA app such as Google Authenticator to enable two factor authentication for your account</h5>
                <hr>
                {% endwith %}
                <h5>Save the private key provided here in a safe place before proceeding. It will not be shared again.</h5>
                <textarea rows="5" style="width: 50%;">{{ private_key }}</textarea><br>
                <hr>
                <a href="{% url 'index' %}"><button class="btn btn-primary">{% trans 'Continue' %}</button></a>
            </div>
        </div>
      </div>
    </div>
  </section>
  <!--   Core JS Files   -->
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  
  <script src="{% static 'js/soft-ui-dashboard.min.js' %}?v=1.0.2"></script>
  
</body>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
</html>
{% endif %}

source/content/templates/main/2fa_old.html
{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% get_current_language as language_code %}
{% if user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <title>
    Blockchain Based Voting
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static 'css/soft-ui-dashboard.css' %}?v=1.0.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper">
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="{% url 'index' %}">Blockchain Based Voting</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ml-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <!-- <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li> -->
              <!-- <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="{% static 'img/anime3.png' %}" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Profile</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Settings</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="{% url 'accounts:log_out' %}" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li> -->
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="content" style="padding-left: 4vw;">
        <div class="row">
          <div class="col-12">
            <h4>{% trans 'Enable 2-FA on your device' %}</h4>
            {% with "/media/"|add:user.username|add:"_qr.png" as qr_dir %}
            <img src="{{ qr_dir }}">
            <br><br>
            <h5>Scan the above QR code on your 2-FA app such as Google Authenticator to enable two factor authentication for your account</h5>
            <hr>
            {% endwith %}
            <a href="{% url 'index' %}"><button class="btn btn-primary">{% trans 'Continue' %}</button></a>
        </div>
      </div>  
    </div>
    </div>
  </div>
</body>
<script src="{% static 'js/core/jquery.min.js' %}"></script>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
</html>
{% endif %}

source/content/templates/main/change_language.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% get_current_language as language_code %}
    {% get_available_languages as languages %}

    <h4>{% trans 'Change language' %}</h4>

    <form action="{% url 'set_language' %}" method="post">

        {% csrf_token %}

        <input name="next" type="hidden" value="{{ redirect_to }}"/>

        <div class="form-group">
            <label class="form-control-label" for="language-field">{% trans 'Select the language' %}</label>
            <select name="language" class="form-control" id="language-field">
                {% for code, name in languages %}
                    <option value="{{ code }}" {% if code == language_code %} selected="selected"{% endif %}>
                        {{ name }} ({{ code }})
                    </option>
                {% endfor %}
            </select>
        </div>

        <button class="btn btn-success">{% trans 'Change' %}</button>

    </form>

{% endblock %}

source/content/templates/main/index.html
{% load bootstrap4 %}
{% load i18n %}
{% load static %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <title>
    Blockchain Based Voting
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- CSS Files -->
  <link href="{% static 'css/soft-ui-dashboard.css' %}?v=1.0.2" rel="stylesheet" />
</head>

<body class="g-sidenav-show   bg-white">
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0  z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="{% url 'index' %}">
              Blockchain Based Voting
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse" id="navigation">
              <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                  <a class="nav-link me-2" href="{% url 'accounts:log_out' %}">
                    <i class="fas fa-user-circle opacity-6 text-dark me-1"></i>
                    Sign Out
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>
  <section>
    <div class="page-header section-height-75">
      <div class="container">
        <div class="row" style="margin-left: -100px;">
          <div class="col-xl-8 col-lg-5 col-md-8 d-flex flex-column mx-auto">
            <div class="card card-plain mt-8">
              <div class="card-header pb-0 text-left bg-transparent">
                <h3 class="font-weight-bolder text-info text-gradient">Welcome back</h3>
            </div>
          </div>
          <div class="col-md-6">
            <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
              <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('{% static 'img/curved-images/curved6.jpg' %}')"></div>
            </div>
          </div>
          <div class="container">
            <div>
                <h1 style="padding-bottom:5%;">Blockchain-based e-voting simulation</h1>
            </div>
            {% if voting_allowed == 'YES' and not user.is_superuser %}
            <h4 style="display: inline;">You are now Eligible to vote</h4>
            <div style="margin-left: 5%; display: inline;">
              <i class="fas fa-check-circle"></i>
            </div>
            <div class="progress">
              <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="75" style="width: 100%"></div>
            </div>

            {% endif %}
            {% if voting_allowed == 'YES' and election.name and not user.is_superuser %}
            <div class="row">
              <div class="col-md-5 menu">
                <h2>{{election.name}}</h2>
                <div class="btn-menu">
                  <a class="btn btn-outline-primary btn-block btn-menu" href="{% url 'ballot:create' %}" role="button">Vote</a>
                </div>
              </div>
              {% endif %}
              {% if user.is_superuser %}
              <div class="col-md-5 menu">
                <h2></h2>
                <p>Verify the voting results</p>
                <h2>{{closed_election.name}}</h2>
                <div class="btn-menu">
                  <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:generate' %}" role="button">Start</a>
                  <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:generate_votes' %}" role="button">Generate Votes</a>
                  <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:transactions' %}" role="button">See transactions (votes)</a>
                  <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:blockchain' %}" role="button">See blocks</a>
                </div>
              </div>
              {% endif %}
            </div>
          </div>
          {% if voting_allowed == '' and not user.is_superuser %}
          <div class="col-md-5 menu">
            <h2>Voting not Allowed</h2>
            <p>Please Update the following details to proceed:</p>
            <ul>
              <li>Aadhaar Card</li>
              <li>Voter ID</li>
              <li>Phone Number</li>
              <li>Address</li>
            </ul>
            <div class="btn-menu">
              <a class="btn btn-outline-primary btn-menu" href="{% url 'accounts:verify' %}" role="button">Proceed to verification</a>
            </div>
          </div>
          {% endif %}
          {% if voting_allowed == 'NO' and not user.is_superuser %}
          <div class="col-md-5 menu">
            <h2>Your details were not approved</h2>
            <p>Please Update the following details once more to proceed:</p>
            <ul>
              <li>Aadhaar Card</li>
              <li>Voter ID</li>
              <li>Phone Number</li>
              <li>Address</li>
            </ul>
            <div class="btn-menu">
              <a class="btn btn-outline-primary btn-menu" href="{% url 'accounts:verify' %}" role="button">Proceed to verification</a>
            </div>
          </div>
          {% endif %}
          {% if voting_allowed == 'PEN' %}
          <div class="col-md-5 menu">
            <h2>Voting not Allowed Yet</h2>
            <p>Your verification process is pending</p>
            <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
            </div>
            <label>ID details uploaded. Pending from voting committee</label>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <!--   Core JS Files   -->
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  
  <script src="{% static 'js/soft-ui-dashboard.min.js' %}?v=1.0.2"></script>
  
</body>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>

</html>