source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView, TOTPPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),
    path('enable_two_fa', TOTPPageView.as_view(), name='enable_two_fa'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/ballot/urls.py
from django.urls import path
from . import views

app_name = 'ballot'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('seal/', views.seal, name='seal')
]

source/ballot/views.py
import time, datetime
import uuid
from django.contrib import messages
from Crypto.Signature import DSS
from Crypto.Hash import SHA3_256
from Crypto.PublicKey import ECC
from Crypto import Random
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import redirect, render
import math
import requests
from accounts.models import Activation
from accounts.utils import mail
from simulation.models import Election, Candidate, Vote, Block, VoteBackup
from firebase import firebase
firebase = firebase.FirebaseApplication('https://pdc-project-25f06-default-rtdb.asia-southeast1.firebasedatabase.app/', None)

def create(request):
    if request.method == 'POST' and request.user.is_authenticated:
        voter_id = request.POST.get('voter-id-input')
        vote = request.POST.get('vote-input')
        private_key = request.POST.get('private-key-input')

        votes_total = Vote.objects.all().count() + 1
        block_id = math.ceil(votes_total/settings.N_TX_PER_BLOCK)

        # Create ballot as string vector
        timestamp = datetime.datetime.now().timestamp() * 10**5
        ballot = "{}|{}|{}".format(voter_id, vote, timestamp)
        print('\ncasted ballot: {}\n'.format(ballot))
        signature = ''
        try:
            # Create signature
            priv_key = ECC.import_key(private_key)
            h = SHA3_256.new(ballot.encode('utf-8'))
            signature = DSS.new(priv_key, 'fips-186-3').sign(h)
            print('\nsignature: {}\n'.format(signature.hex()))
            print(private_key)

            # Verify the signature using registered public key
            public_key = Activation.objects.filter(user_id = request.user.id)[0]
            print(public_key.public_key_ecc)
            pub_key = ECC.import_key(public_key.public_key_ecc)
            verifier = DSS.new(pub_key, 'fips-186-3')
        
            print(verifier.verify(h, signature))
            status = 'The ballot is signed successfully.'
            new_vote = Vote(id=voter_id, vote=vote, timestamp=timestamp, block_id=block_id)
            vote_data = {'Id': voter_id,
                    'Vote': vote,
                    'Timestamp': timestamp,
                    'Block_Id': block_id,
                    }
            requests.put('https://pdc-project-25f06-default-rtdb.asia-southeast1.firebasedatabase.app/voter_data.json', vote_data)
            new_backup_vote = VoteBackup(id=voter_id, vote=vote, timestamp=timestamp, block_id=block_id)
            new_vote.save()
            new_backup_vote.save()
            election = Election.objects.filter(is_open = True).first()
            mail("Your vote has been cast successfully", request.user.email, str(election.name) + " - Voting Successful")
            error = False
        except (ValueError, TypeError):
            status = 'The key is not registered.'
            error = True
            messages.info(request, status, extra_tags='bg-info')
        context = {
            'ballot': ballot,
            'signature': signature,
            'status': status,
            'error': error,
        }
        return redirect('index')
    if request.user.is_authenticated:
        election = Election.objects.filter(is_open = True).first()
        candidates = Candidate.objects.filter(election = election.id)
        context = {'voter_id': uuid.uuid4(), 'election': election, 'candidates': candidates}
        return render(request, 'ballot/create.html', context)
    else:
        return redirect('index')

def seal(request):
    print("HERE")
    if request.method == 'POST' and request.user.is_authenticated:
        ballot = request.POST.get('ballot_input')
        ballot_byte = ballot.encode('utf-8')
        ballot_hash = SHA3_256.new(ballot_byte).hexdigest()
        # Puzzle requirement: '0' * n (n leading zeros)
        puzzle, pcount = settings.PUZZLE, settings.PLENGTH
        nonce = 0

        # Try to solve puzzle
        start_time = time.time() # benchmark
        timestamp = datetime.datetime.now().timestamp() # mark the start of mining effort
        while True:
            block_hash = SHA3_256.new(("{}{}{}".format(ballot, nonce, timestamp).encode('utf-8'))).hexdigest()
            print('\ntrial hash: {}\n'.format(block_hash))
            if block_hash[:pcount] == puzzle:
                stop_time = time.time() # benchmark
                print("\nblock is sealed in {} seconds\n".format(stop_time-start_time))
                break
            nonce += 1
        

        context = {
            'prev_hash': 'GENESIS',
            'transaction_hash': ballot_hash,
            'nonce': nonce,
            'block_hash': block_hash,
            'timestamp': timestamp,
        }
        return render(request, 'ballot/seal.html', context)
    if request.user.is_authenticated:
        return redirect('ballot:create')
    else:
        return redirect('index')

source/ballot/templates/ballot/create.html
{% extends 'base.html' %}
{% load static %}
{% block title_bl %}Create ballot{% endblock %}
{% block body_bl %}
<div class="container" style="margin-top: 100px; border: 1px solid black; background-color: #F5F5F5;">
    <h1 style="text-align:center;">{{election.name}}</h1>
    <form action="{% url 'ballot:create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="voter-id-input">UUID:</label>
            <input name="voter-id-input" type="text" class="form-control" id="voter-id-input" placeholder="fe021e59-c29d-4532-9e99-5c42f1910af3" value="{{ voter_id }}" required autofocus>
        </div>
        <div id="candidate" style="padding:20px 0;">
            <p style="text-align:center;">Eligible candidates are shown below:</p>
            <div class="row">
                {% for candidate in candidates %}
                    <div class="col-md-4">
                        {% with "fas fa-5x fa-"|add:candidate.symbol as icon %}
                        <i class="{{icon}}"></i>
                        {% endwith %}
                        <p style="text-align: center;">{{candidate.name}}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
                <label for="vote-input">Your candidate choice:</label>
                <input name="vote-input" type="number" class="form-control" id="voter-input" placeholder="Enter valid candidate ID" min="1" max="3" required>
            </div>
        <div class="form-group">
            <label for="private-key-textarea">Your private key:</label>
            <textarea name="private-key-input" class="form-control" id="private-key-textarea" rows="10" required></textarea>
            <small id="privatekeyHelpBlock" class="form-text text-muted">
                The matching public key must already be registered.
            </small>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Submit ballot</button>
    </form>
</div>
{% endblock %}

source/ballot/templates/ballot/seal.html
{% extends 'base.html' %}
{% load static %}
{% load sim_filters %}
{% block title_bl %}Block detail{% endblock %}

{% block body_bl %}
    <div class="container">
        <h1>Block detail</h1>
        <div style="padding:3%; border: 1px solid black;">
            <dl class="row">
                <dt class="col-sm-3">Previous hash</dt>
                <dd class="">{{ prev_hash }}</dd>
    
                <dt class="col-sm-3">Transaction hash</dt>
                <dd class=""><code>{{ transaction_hash }}</code></dd>
    
                <dt class="col-sm-3">Block hash</dt>
                <dd class=""><code>{{ block_hash }}</code></dd>
    
                <dt class="col-sm-3">Nonce</dt>
                <dd class="">{{ nonce }}</dd>
    
                <dt class="col-sm-3">Timestamp</dt>
                <dd class="">{{ timestamp }} ({{ timestamp}})</dd>
            </dl>
            <a class="btn btn-primary btn-small" href="{% url 'welcome:home' %}" role="button">Back to homepage</a>
        </div>
    </div>
{% endblock %}

source/ballot/templates/ballot/status.html
{% extends 'base.html' %}
{% block title_bl %}Status{% endblock %}

{% block body_bl %}
<div class="container">
    <h1>Signature Verification</h1>
    <div style="padding:3%; border:1px solid black;">
        <p>Your ballot was <code>{{ ballot }}</code></p>
        <p>Generated signature <code>{{ signature }}</code></p><br>
        <p style="color:{% if error %}red{% else %}green{% endif %};">
            {{ status }}
        </p>
    
        {% if not error %}
        <form action="{% url 'ballot:seal' %}" method="POST">
            {% csrf_token %}
            <input name="ballot_input" type="hidden" value="{{ ballot }}">
            <button type="submit" class="btn btn-primary btn-block">Seal the ballot</button>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}