source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView, TOTPPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),
    path('enable_two_fa', TOTPPageView.as_view(), name='enable_two_fa'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/simulation/urls.py
from django.urls import path
from . import views

app_name = 'simulation'
urlpatterns = [
    path('generate/', views.generate, name='generate'),
    path('generate_votes/', views.generate_votes, name='generate_votes'),
    path('seal/', views.seal, name='seal'),
    path('transactions/', views.transactions, name='transactions'),
    path('blockchain/', views.blockchain, name='blockchain'),
    path('block/<str:block_hash>/', views.block_detail, name='block_detail'),
    path('verify/', views.verify, name='verify'),
    path('sync/', views.sync, name='sync'),
    path('sync_with_firebase/', views.sync_with_firebase, name='sync_with_firebase'),
    path('sync_block/<int:block_id>/', views.sync_block, name='sync_block'),
]

source/simulation/models.py
import datetime, uuid, random
from django.db import models
from django.contrib import admin

def get_vote():
    return random.randint(1, 3)

def get_timestamp():
    return datetime.datetime.now().timestamp()

class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    vote = models.IntegerField(default=get_vote)
    timestamp = models.FloatField(default=get_timestamp)
    block_id = models.IntegerField(null=True)

    def __str__(self):
        return "{}|{}|{}".format(self.id, self.vote, self.timestamp)

class Block(models.Model):
    prev_h = models.CharField(max_length=64, blank=True)
    merkle_h = models.CharField(max_length=64, blank=True)
    h = models.CharField(max_length=64, blank=True)
    nonce = models.IntegerField(null=True)
    timestamp = models.FloatField(default=get_timestamp)

    def __str__(self):
        return str(self.id)

class VoteBackup(models.Model):
    """This model acts as backup; its objects shall never be tampered."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    vote = models.IntegerField(default=get_vote)
    timestamp = models.FloatField(default=get_timestamp)
    block_id = models.IntegerField(null=True)

    def __str__(self):
        return "{}|{}|{}".format(self.id, self.vote, self.timestamp)

class Election(models.Model):
    name = models.CharField(max_length=64)
    is_open = models.BooleanField()
    
    def __str__(self):
        return str(self.name)

class Candidate(models.Model):
    name = models.CharField(max_length=64)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    party = models.CharField(max_length=64)
    symbol = models.CharField(max_length=64)

    def __str__(self):
        return str(self.name)
    
admin.site.register(Election)
admin.site.register(Candidate)

source/simulation/views.py
import datetime, time, json, math
import random
import uuid
import os
import requests
from Crypto.Hash import SHA3_256
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.safestring import mark_safe
from simulation.models import Election, Candidate
from app.conf.development.settings import *
from django.db import transaction
from .models import Vote, Block, VoteBackup, Election, Candidate

from firebase import firebase
firebase = firebase.FirebaseApplication('https://pdc-project-25f06-default-rtdb.asia-southeast1.firebasedatabase.app/', None)

def generate(request):
    number_of_tx_per_block = settings.N_TX_PER_BLOCK
    # Generate transactions.
    time_start = time.time()
    block_no = 1
    all_votes = Vote.objects.all()
    for i in range(len(all_votes)):
        # generate random, valid values
        v_id = all_votes[i].id
        v_cand = all_votes[i].vote
        v_timestamp = all_votes[i].timestamp
        # directly fill the values and the block id for simulation purpose
        new_vote = Vote(id=v_id, vote=v_cand, timestamp=v_timestamp, block_id=block_no)
        new_backup_vote = VoteBackup(id=v_id, vote=v_cand, timestamp=v_timestamp, block_id=block_no)
        # "Broadcast" to two nodes
        #new_vote.save()
        #new_backup_vote.save()
        print("#{} new vote: {}".format(i, new_vote)) # for sanity
        if i % number_of_tx_per_block == 0:
            block_no += 1
    time_end = time.time()
    print('\nFinished in {} seconds.\n'.format(time_end - time_start))

    # View the generated transactions
    votes = Vote.objects.order_by('-timestamp')[:100] # only shows the last 100, if any
    election = Election.objects.filter(is_open = False).first()
    candidates = Candidate.objects.filter(election = election.id)
    context = {
        'votes': votes,
        'election': election,
        'candidates': candidates
    }
    request.session['transactions_done'] = True
    return render(request, 'simulation/generate.html', context)

def generate_votes(request):
    #"""Generate transactions and fill them with valid values."""
    number_of_transactions = Vote.objects.all().count()
    number_of_tx_per_block = settings.N_TX_PER_BLOCK

    # Delete all data from previous demo.
    deleted_old_votes = Vote.objects.all().delete()[0]
    VoteBackup.objects.all().delete()
    print('\nDeleted {} data from previous simulation.\n'.format(deleted_old_votes))
    # Delete all blocks from previous demo.
    deleted_old_blocks = Block.objects.all().delete()[0]
    print("\nDeleted {} blocks from previous simulation.\n".format(deleted_old_blocks))
    
    # Generate transactions.
    time_start = time.time()
    block_no = 1
    vote_dict = "{"
    transaction.set_autocommit(False, using=None)
    prev_timestamp = None
    for i in range(1, N_TRANSACTIONS + 1):
        # generate random, valid values
        v_id = uuid.uuid4()
        v_cand = random.randint(1,2)
        v_timestamp = datetime.datetime.now().timestamp() * 10**5
        if v_timestamp == prev_timestamp:
            v_timestamp += 1
        prev_timestamp = v_timestamp
        # directly fill the values and the block id for simulation purpose
        new_vote = Vote(id=v_id, vote=v_cand, timestamp=v_timestamp, block_id=block_no)
        new_backup_vote = VoteBackup(id=v_id, vote=v_cand, timestamp=v_timestamp, block_id=block_no)
        # "Broadcast" to two nodes
        new_vote.save()
        new_backup_vote.save()
        if i == N_TRANSACTIONS:
            vote_data = '"' + str(v_id) + '" : {"Vote" : "' + str(v_cand) + '", "Timestamp" : "' + str(v_timestamp) + '", "Block_Id" : "' + str(block_no) + '"}'
        else:
            vote_data = '"' + str(v_id) + '" : {"Vote" : "' + str(v_cand) + '", "Timestamp" : "' + str(v_timestamp) + '", "Block_Id" : "' + str(block_no) + '"}, '
        vote_dict = vote_dict + vote_data
        print("#{} new vote: {}".format(i, new_vote)) # for sanity
        if i % number_of_tx_per_block == 0:
            block_no += 1
    transaction.commit()
    transaction.set_autocommit(True, using=None)    
    requests.put('https://pdc-project-25f06-default-rtdb.asia-southeast1.firebasedatabase.app/voter_data.json', vote_dict + "}")
    time_end = time.time()
    print('\nFinished in {} seconds.\n'.format(time_end - time_start))
    # View the generated transactions
    votes = Vote.objects.order_by('-timestamp')[:100] # only shows the last 100, if any
    election = Election.objects.filter(is_open = False).first()
    candidates = Candidate.objects.filter(election = election.id)
    context = {'votes': votes, 'election': election, 'candidates': candidates}
    request.session['transactions_done'] = True
    return render(request, 'simulation/generate.html', context)

def seal(request):
    """Seal the transactions generated previously."""
    exec(open("./mining.py").read())
    n = 0
    number_of_blocks = math.ceil(Vote.objects.all().count()/settings.N_TX_PER_BLOCK)
    while(True):
        if n == number_of_blocks:
            break
        time.sleep(2)
        latest_block = Block.objects.filter(id = n + 1)
        if len(latest_block):
            n += 1

    # if request.session.get('transactions_done') is None:
    #     redirect('index')
    # del request.session['transactions_done']

    # Puzzle requirement: '0' * (n leading zeros)
    return redirect('simulation:blockchain')

def transactions(request):
    """See all transactions that have been contained in blocks."""
    vote_list = Vote.objects.all().order_by('timestamp')
    paginator = Paginator(vote_list, 100, orphans=20, allow_empty_first_page=True)

    page = request.GET.get('page')
    votes = paginator.get_page(page)

    hashes = [SHA3_256.new(str(v).encode('utf-8')).hexdigest() for v in votes]
    
    # This happens if you don't use foreign key
    block_hashes = []
    for i in range(0, len(votes)):
        try:
            b = Block.objects.get(id=votes[i].block_id)[0]
            h = b.h
        except:
            h = 404
        block_hashes.append(h)
    
    # zip the three iters
    votes_pg = votes # for pagination
    votes = zip(votes, hashes, block_hashes)

    election = Election.objects.filter(is_open = False)
    if(len(election)):
        election = Election.objects.filter(is_open = False).first()
        candidates = Candidate.objects.filter(election_id = election.id)
    else:
        election = []
        candidates = []
    # Calculate the voting result of 3 cands, the ugly way
    result = []
    for i in range(len(candidates)):
        try:
            r = Vote.objects.filter(vote=i+1).count()
        except:
            r = 0
        result.append(r)

    context = {
        'votes': votes,
        'result': result,
        'candidates': candidates,
        'election': election,
        'votes_pg': votes_pg,

    }
    return render(request, 'simulation/transactions.html', context)

def blockchain(request):
    """See all mined blocks."""
    blocks = Block.objects.all().order_by('id')
    context = {
        'blocks': blocks,
    }
    return render(request, 'simulation/blockchain.html', context)

def verify(request):
    """Verify transactions in all blocks by re-calculating the merkle root."""
    # Basically, by just creating a session (message) var

    print('verifying data...')
    number_of_blocks = Block.objects.all().count()
    corrupt_block_list = ''
    transactions_from_firebase = firebase.get('/voter_data','')
    vote_verification_message = ""
    for i in range(1, number_of_blocks + 1):
        # Select block #i
        b = Block.objects.get(id=i)
        # Select all transactions in block #i
        transactions = Vote.objects.filter(block_id=i).order_by('timestamp')
        for vote in transactions:
            vote_obj = transactions_from_firebase[str(vote.id)]
            if vote_obj['Vote'] != str(vote.vote):
                vote_verification_message = vote_verification_message + "<br/>Vote ID: " + str(vote.id) + " is tampered"
                print("Vote ID: " + str(vote.id) + " is tampered\n")            

        # Verify them
        root = MerkleTools()
        root.add_leaf([str(tx) for tx in transactions], True)
        root.make_tree()
        merkle_h = root.get_merkle_root()
        
        if b.merkle_h == merkle_h:
            message = 'Block {} verified.'.format(i)
        else:
            message = 'Block {} is TAMPERED'.format(i)
            corrupt_block_list += ' {}'.format(i)
        print('{}'.format(message))
    if len(corrupt_block_list) > 0:
        messages.warning(request, mark_safe('The following blocks have corrupted transactions: {}. \n {}'.format(corrupt_block_list, vote_verification_message)), extra_tags='bg-danger')
    else:
        messages.info(request, 'All transactions in blocks are intact.', extra_tags='bg-info')
    return redirect('simulation:blockchain')

def sync(request):
    """Restore transactions from honest node."""
    deleted_old_votes = Vote.objects.all().delete()[0]
    print('\nTrying to sync {} transactions with 1 node(s)...\n'.format(deleted_old_votes))
    bk_votes = VoteBackup.objects.all().order_by('timestamp')
    transaction.set_autocommit(False, using=None)
    for bk_v in bk_votes:
        vote = Vote(id=bk_v.id, vote=bk_v.vote, timestamp=bk_v.timestamp, block_id=bk_v.block_id)
        vote.save()
    transaction.commit()
    transaction.set_autocommit(True, using=None)
    print('\nSync complete.\n')
    messages.info(request, 'All blocks have been synced successfully.')
    return redirect('simulation:blockchain')

def sync_with_firebase(request):
    """Restore transactions from firebase."""
    deleted_old_votes = Vote.objects.all().delete()[0]

source/simulation/templates/simulation/block.html
{% extends 'base.html' %}
{% load static %}
{% load sim_filters %}
{% block title_bl %}Block #{{ bk.pk }}{% endblock %}

{% block body_bl %}
<div class="container">
    <h1 class="pb-1">Block #{{ bk.id }}</h1>
    <a class="btn btn-light btn-sm" href="{% url 'simulation:blockchain' %}" role="button">Back to blocks list</a>
    <a class="btn btn-light btn-sm" href="{% url 'index' %}" role="button">Back to homepage</a>
    <div class="mt-1">
        <dl class="row">
            <dt class="col-sm-3">Previous hash</dt>
            <dd class=""><code>{{ bk.prev_h }}</code></dd>

            <dt class="col-sm-3">Merkle root hash</dt>
            <dd class=""><code>{{ bk.merkle_h }}</code></dd>

            <dt class="col-sm-3">Block hash</dt>
            <dd class=""><code>{{ bk.h }}</code></dd>

            <dt class="col-sm-3">Nonce</dt>
            <dd class="">{{ bk.nonce }}</dd>

            <dt class="col-sm-3">Timestamp</dt>
            <dd class="">{{ bk.timestamp }}</dd>

            <dt class="col-sm-3">Confirmations</dt>
            <dd class="">{{ confirmed_by }} confirmations</dd>
        </dl>
    </div>
    <div class="p-2" id="block-navigation">
        {% if prev_block %}
            <a class="btn btn-primary btn-sm" href="{% url 'simulation:block_detail' block_hash=prev_block.h %}" role="button">Previous block</a>
        {% endif %}
        {% if next_block %}
            <a class="btn btn-primary btn-sm" href="{% url 'simulation:block_detail' block_hash=next_block.h %}" role="button">Next block</a>
        {% endif %}
    </div>
    <div>
        <h2>Transactions</h2>
        <p>Re-calculated merkle root hash: <code>{{ verified_merkle_h }}</code></p>
        {% if tampered %}
        <div class="bg-danger text-white">
            <p>Transactions are tampered <a class="btn btn-primary btn-sm" href="{% url 'simulation:sync_block' block_id=bk.id %}" role="button">Sync with other nodes</a></p>
        </div>
        {% else %}
            <div class="bg-success text-white">
                <p>Transactions are not tampered</p>
            </div>
        {% endif %}

        <small>Showing page {{ transactions_pg.number }} of {{ transactions_pg.paginator.num_pages }}</small>
        <div class="pagination pb-2">
            <span class="step-links">
                {% if transactions_pg.has_previous %}
                    <a class="btn btn-light btn-sm" href="?page=1" role="button">&laquo; First</a>
                    <a class="btn btn-light btn-sm" href="?page={{ transactions_pg.previous_page_number }}" role="button">Previous</a>
                {% endif %}
                {% if transactions_pg.has_next %}
                    <a class="btn btn-light btn-sm" href="?page={{ transactions_pg.next_page_number }}" role="button">Next</a>
                    <a class="btn btn-light btn-sm" href="?page={{ transactions_pg.paginator.num_pages }}" role="button">Last &raquo;</a>
                {% endif %}
            </span>
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Voter ID</th>
                    <th scope="col">Cand</th>
                    <th scope="col">Timestamp</th>
                    <th scope="col">Hash</th>
                </tr>
            </thead>
            <tbody>
                {% for t, h in transactions %}
                <tr>
                    <td>{{ forloop.counter }}</th>
                    <td><code>{{ t.id }}</code></td>
                    <td>{{ t.vote }}</td>
                    <td>{{ t.timestamp }}</td>
                    <td title="{{ h }}"><code>{{ h|truncatechars:32 }}</code></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

source/simulation/templates/simulation/blockchain.html
{% extends 'base.html' %}
{% load sim_filters %}
{% block title_bl %}Blocks{% endblock %}

{% block body_bl %}
<div class="container">
    <h1>List of blocks</h1>
    <a class="btn btn-light btn-sm" href="{% url 'simulation:transactions' %}" role="button">See all transactions</a>
    <a class="btn btn-light btn-sm" href="{% url 'index' %}" role="button">Back to homepage</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Previous Hash</th>
                <th scope="col">Block Hash</th>
                <th scope="col">Merkle Root Hash</th>
                <th scope="col">Nonce</th>
                <th scope="col">Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for block in blocks %}
            <tr>
                <td><a href="{% url 'simulation:block_detail' block_hash=block.h %}">{{ block.id }}</a></th>
                <td title="{{ block.prev_h }}"><code>{{ block.prev_h|truncatechars:30 }}</code></td>
                <td title="{{ block.h }}"><code>{{ block.h|truncatechars:30 }}</code></td>
                <td title="{{ block.merkle_h }}"><code>{{ block.merkle_h|truncatechars:30 }}</code></td>
                <td>{{ block.nonce }}</td>
                <td>{{ block.timestamp }}</td>
            </tr>
            {% empty %}
                <p>No record.</p>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-outline-primary btn-block" href="{% url 'simulation:verify' %}" role="button" title="Verify all transactions in each block">Verify Votes</a>
    <a class="btn btn-outline-primary btn-block" href="{% url 'simulation:sync' %}" role="button" title="Sync data with virtual nodes">Sync Local Backup</a>
    <a class="btn btn-outline-primary btn-block" href="{% url 'simulation:sync_with_firebase' %}" role="button" title="Sync data with Firebase">Sync Firebase</a>
</div>
{% endblock %}

source/simulation/templates/simulation/generate.html
{% extends 'base.html' %}
{% block title_bl %}Transactions{% endblock %}

{% block body_bl %}
<div class="container">
    <h1>List of unconfirmed votes</h1>
    <p>Showing last 100 transactions (or all if &lt;=100)</p>
    
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Voter ID</th>
                <th scope="col">Vote</th>
                <th scope="col">Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for ballot in votes %}
            <tr>
                <td><code>{{ ballot.id }}</code></th>
                <td>{{ ballot.vote }}</td>
                <td>{{ ballot.timestamp }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <a class="btn btn-primary btn-block" href="{% url 'simulation:seal' %}" role="button">Mine into blocks</a>
</div>
{% endblock %}

source/simulation/templates/simulation/transactions.html
{% extends 'base.html' %}
{% load sim_filters %}
{% block title_bl %}Transactions{% endblock %}

{% block body_bl %}
<div class="container">
    <h1 style="width: 200%;">List of confirmed votes - {{election.name}}</h1>
    <a class="btn btn-light btn-sm" href="{% url 'simulation:blockchain' %}" role="button">See all blocks</a>
    <a class="btn btn-light btn-sm" href="{% url 'index' %}" role="button">Back to homepage</a>
    <div style="margin:1%; padding:1%; border:1px solid black;">
        {% for c in candidates %}
            Candidate #{{ forloop.counter }}: {{c.name}}<br>
        {% endfor %}
    </div>
    <div style="margin:1%; padding:1%; border:1px solid black;">
        {% for r in result %}
            Candidate #{{ forloop.counter }}: {{ r }} votes<br>
        {% endfor %}
    </div>

    <small>Showing page {{ votes_pg.number }} of {{ votes_pg.paginator.num_pages }}</small>
    <div class="pagination pb-2">
        <span class="step-links">
            {% if votes_pg.has_previous %}
                <a class="btn btn-light btn-sm" href="?page=1" role="button">&laquo; First</a>
                <a class="btn btn-light btn-sm" href="?page={{ votes_pg.previous_page_number }}" role="button">Previous</a>
            {% endif %}
            {% if votes_pg.has_next %}
                <a class="btn btn-light btn-sm" href="?page={{ votes_pg.next_page_number }}" role="button">Next</a>
                <a class="btn btn-light btn-sm" href="?page={{ votes_pg.paginator.num_pages }}" role="button">Last &raquo;</a>
            {% endif %}
        </span>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Voter ID</th>
                <th scope="col">Vote</th>
                <th scope="col">Timestamp</th>
                <th scope="col">Hash</th>
                <th scope="col">Block</th>
            </tr>
        </thead>
        <tbody>
            {% for ballot, h, bh in votes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><code>{{ ballot.id }}</code></th>
                <td>{{ ballot.vote }}</td>
                <td>{{ ballot.timestamp }}</td>
                <td title="{{ h }}"><code>{{ h|truncatechars:20 }}</code></td>
                <td><a class="btn btn-light btn-sm" href="{% url 'simulation:block_detail' block_hash=bh %}" role="button">go to block</a></td>
            </tr>
            {% empty %}
                <p>No record.</p>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}